### ISSUE TITLE
The sidebar menu didn't collapse when hovering.

### ISSUE THREAD

**Issue by R3JMW** [ng-matero/ng-matero#95] opened 2021-04-29 13:11 UTC
Hey, I'm glad it's a specific solution expect the PrimeNG for Angular.
It's a great job for all the components was been designed and implemented by yourself.

Here's a tiny issue for the sidebar behavior. You can see when the sidebar menu collapse but the sub level menu didn't collapse which looks strange.
![image](https://user-images.githubusercontent.com/45484888/116555476-06f1d080-a92f-11eb-9787-a37ba3a6400a.png)

**Comment by nzbin** [comment] 2021-04-29 14:37
Duplicate of #56

**Closed** 2021-07-03 14:15 UTC
Labels: duplicate, menu
