### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by someshwarjadhav** [ng-matero/ng-matero#569] opened 2023-09-13 10:07 UTC
I am trying for login using my api but i can't  please help me it also gives me error for navigate i.e i cannot be able to access dashboard

**Comment by nzbin** [comment] 2023-09-13 10:09
Duplicate of #567

**Comment by nzbin** [comment] 2023-09-13 10:10
Can you ask on the issue #567? Please don't submit the same issue!

**Closed by nzbin** 2023-09-13 10:10 UTC
