### ISSUE TITLE
Related to login

### ISSUE THREAD

**Issue by someshwarjadhav** [ng-matero/ng-matero#568] opened 2023-09-12 11:53 UTC
Actually i want to use my own api of POST for login but you have used /auth/login so it gives me error routernavigation and also it givas response false 
what should i do for this .... and i want to pass username and password dynamically instead of passing static

**Comment by nzbin** [comment] 2023-09-12 12:50
Duplicate of #567

**Closed by nzbin** 2023-09-12 12:50 UTC
Labels: duplicate

**Comment by seyfer** [comment] 2023-11-15 09:19
@nzbin please add docs for that there https://nzbin.gitbook.io/ng-matero/authentication
