### ISSUE TITLE
issue for routing

### ISSUE THREAD

**Issue by someshwarjadhav** [ng-matero/ng-matero#585] opened 2023-10-10 07:42 UTC
i am on my dashboard and now i want to navigate to another page but when i click on another page firstly blank page appears and when i click second time it opens give me a solution

**Comment by nzbin** [comment] 2023-10-11 01:36
I wonder why you always submit duplicated issue, can you add comments in #578?
Duplicate of #578

**Closed** 2023-10-11 01:36 UTC
Labels: duplicate
