### ISSUE TITLE
Add support for material 3

### ISSUE THREAD

**Issue by blackholegalaxy** [ng-matero/ng-matero#667] opened 2024-04-13 13:29 UTC
Hi! Angular material evolved recently migrating progressively to Material 3, especially for general style and look and feel.

When is ng-matero planned to go with this new styling? Or at least allow for an alternative.

Example on buttons

Material 2 styling on v16:
![image](https://github.com/ng-matero/ng-matero/assets/11064123/31a12f37-d649-4962-b9ac-ad1b4d04c6f9)

Material 3 styling on v17:
![image](https://github.com/ng-matero/ng-matero/assets/11064123/af1082f8-e778-4b2f-91d4-eb9122f1ad8b)

**Comment by nzbin** [comment] 2024-04-15 07:11
As the Material Extensions has also switched Material 3, you can improve the styles by yourself. I will update the styles when the Material 3 is not experimental.

**Comment by nzbin** [comment] 2024-06-18 03:30
Duplicate of #678

**Closed by nzbin** 2024-06-18 03:30 UTC
Labels: enhancement
