### ISSUE TITLE
`@material/elevation/elevation-theme` stylsheet not found since `@angular/material` 18.1.2

### ISSUE THREAD

**Issue by GKersten** [ng-matero/ng-matero#709] opened 2024-07-26 09:30 UTC
After upgrading `@angular/material` to v18.1.2, when building our app we are getting errors because `@ng-matero\extensions` is unable to import the stylesheet `@material/elevation/elevation-theme`.

````
./src/styles/styles.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
  ╷
4 │ @use '@material/elevation/elevation-theme' as mdc-elevation-theme;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@ng-matero\extensions\core\tokens\_token-utils.scss 4:1  @use
  node_modules\@ng-matero\extensions\alert\_alert-theme.scss 5:1        @forward
  node_modules\@ng-matero\extensions\_index.scss 1:1                    @use
  src\styles\third-party\angular-material.scss 2:1                      @import
  src\styles\styles.scss 1:9                                            root stylesheet

./src/styles/styles.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
  ╷
4 │ @use '@material/elevation/elevation-theme' as mdc-elevation-theme;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@ng-matero\extensions\core\tokens\_token-utils.scss 4:1  @use
  node_modules\@ng-matero\extensions\alert\_alert-theme.scss 5:1        @forward
  node_modules\@ng-matero\extensions\_index.scss 1:1                    @use
  src\styles\third-party\angular-material.scss 2:1                      @import
  src\styles\styles.scss 1:9                                            root stylesheet
````

Turns out since `@angular/material` v18.1.2 the package.json no longer has a dependency on `@material/` packages:
https://www.npmjs.com/package/@angular/material/v/18.1.2?activeTab=code

See the related PR on Angular repo here:
https://github.com/angular/components/pull/29472

And the specific commit:
https://github.com/angular/components/pull/29472/commits/4abafe2e9e297b3ae9357b8bc9380873f17483cc#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Apparently the `@material` packages are not needed anymore, is this still required for `@ng-matero` to work correctly?

**Comment by GKersten** [comment] 2024-07-26 09:44
Work-around for now seems to be to just add this list of dependencies to my own `package.json`, but I guess this requires some changes in this package.

````
  "dependencies": {
    ...
    "@material/animation": "15.0.0-canary.7f224ddd4.0",
    "@material/auto-init": "15.0.0-canary.7f224ddd4.0",
    "@material/banner": "15.0.0-canary.7f224ddd4.0",
    "@material/base": "15.0.0-canary.7f224ddd4.0",
    "@material/button": "15.0.0-canary.7f224ddd4.0",
    "@material/card": "15.0.0-canary.7f224ddd4.0",
    "@material/checkbox": "15.0.0-canary.7f224ddd4.0",
    "@material/chips": "15.0.0-canary.7f224ddd4.0",
    "@material/circular-progress": "15.0.0-canary.7f224ddd4.0",
    "@material/data-table": "15.0.0-canary.7f224ddd4.0",
    "@material/density": "15.0.0-canary.7f224ddd4.0",
    "@material/dialog": "15.0.0-canary.7f224ddd4.0",
    "@material/dom": "15.0.0-canary.7f224ddd4.0",
    "@material/drawer": "15.0.0-canary.7f224ddd4.0",
    "@material/elevation": "15.0.0-canary.7f224ddd4.0",
    "@material/fab": "15.0.0-canary.7f224ddd4.0",
    "@material/feature-targeting": "15.0.0-canary.7f224ddd4.0",
    "@material/floating-label": "15.0.0-canary.7f224ddd4.0",
    "@material/form-field": "15.0.0-canary.7f224ddd4.0",
    "@material/icon-button": "15.0.0-canary.7f224ddd4.0",
    "@material/image-list": "15.0.0-canary.7f224ddd4.0",
    "@material/layout-grid": "15.0.0-canary.7f224ddd4.0",
    "@material/line-ripple": "15.0.0-canary.7f224ddd4.0",
    "@material/linear-progress": "15.0.0-canary.7f224ddd4.0",
    "@material/list": "15.0.0-canary.7f224ddd4.0",
    "@material/material-color-utilities": "^0.2.7",
    "@material/menu": "15.0.0-canary.7f224ddd4.0",
    "@material/menu-surface": "15.0.0-canary.7f224ddd4.0",
    "@material/notched-outline": "15.0.0-canary.7f224ddd4.0",
    "@material/radio": "15.0.0-canary.7f224ddd4.0",
    "@material/ripple": "15.0.0-canary.7f224ddd4.0",
    "@material/rtl": "15.0.0-canary.7f224ddd4.0",
    "@material/segmented-button": "15.0.0-canary.7f224ddd4.0",
    "@material/select": "15.0.0-canary.7f224ddd4.0",
    "@material/shape": "15.0.0-canary.7f224ddd4.0",
    "@material/slider": "15.0.0-canary.7f224ddd4.0",
    "@material/snackbar": "15.0.0-canary.7f224ddd4.0",
    "@material/switch": "15.0.0-canary.7f224ddd4.0",
    "@material/tab": "15.0.0-canary.7f224ddd4.0",
    "@material/tab-bar": "15.0.0-canary.7f224ddd4.0",
    "@material/tab-indicator": "15.0.0-canary.7f224ddd4.0",
    "@material/tab-scroller": "15.0.0-canary.7f224ddd4.0",
    "@material/textfield": "15.0.0-canary.7f224ddd4.0",
    "@material/theme": "15.0.0-canary.7f224ddd4.0",
    "@material/tooltip": "15.0.0-canary.7f224ddd4.0",
    "@material/tokens": "15.0.0-canary.7f224ddd4.0",
    "@material/top-app-bar": "15.0.0-canary.7f224ddd4.0",
    "@material/touch-target": "15.0.0-canary.7f224ddd4.0",
    "@material/typography": "15.0.0-canary.7f224ddd4.0",
    ...
}
````

**Comment by nzbin** [comment] 2024-07-26 11:33
Duplicate of https://github.com/ng-matero/extensions/issues/326, `extensions@18.1.1` has fixed.

**Closed** 2024-07-29 09:20 UTC
Labels: duplicate
